// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bpm_mcp_api.Data;

#nullable disable

namespace bpm_mcp_api.Migrations
{
    [DbContext(typeof(BpmDbContext))]
    [Migration("20260121020616_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("bpm_mcp_api.Models.Asset", b =>
                {
                    b.Property<string>("AssetNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Employee")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsForReplacement")
                        .HasColumnType("bit");

                    b.HasKey("AssetNo");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            AssetNo = "LAPTOP001",
                            Category = "Computer Equipment",
                            Description = "Dell Latitude 7420 Laptop",
                            Employee = "john.doe",
                            IsForReplacement = false
                        },
                        new
                        {
                            AssetNo = "DESK001",
                            Category = "Office Furniture",
                            Description = "Standing Desk - Height Adjustable",
                            Employee = "john.doe",
                            IsForReplacement = false
                        },
                        new
                        {
                            AssetNo = "MON002",
                            Category = "Computer Equipment",
                            Description = "LG UltraWide 34-inch Monitor",
                            Employee = "jane.smith",
                            IsForReplacement = true
                        });
                });

            modelBuilder.Entity("bpm_mcp_api.Models.AssetType", b =>
                {
                    b.Property<string>("ProductId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Specs")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ProductId");

                    b.ToTable("AssetTypes");

                    b.HasData(
                        new
                        {
                            ProductId = "LAPTOP-DL-7420",
                            Description = "Dell Latitude 7420 Business Laptop",
                            Price = 1899.99m,
                            Specs = "Intel i7-1185G7, 16GB RAM, 512GB SSD, 14-inch FHD"
                        },
                        new
                        {
                            ProductId = "MON-LG-34WN",
                            Description = "LG UltraWide 34-inch Curved Monitor",
                            Price = 699.99m,
                            Specs = "3440x1440 resolution, USB-C, HDR10"
                        },
                        new
                        {
                            ProductId = "DESK-SD-001",
                            Description = "Standing Desk - Electric Height Adjustable",
                            Price = 599.99m,
                            Specs = "48x24 inch surface, Memory settings, Cable management"
                        },
                        new
                        {
                            ProductId = "CHAIR-ERG-01",
                            Description = "Ergonomic Office Chair with Lumbar Support",
                            Price = 449.99m,
                            Specs = "Mesh back, Adjustable armrests, 5-year warranty"
                        },
                        new
                        {
                            ProductId = "PHONE-IP15P",
                            Description = "iPhone 15 Pro",
                            Price = 999.99m,
                            Specs = "128GB, Titanium, A17 Pro chip"
                        });
                });

            modelBuilder.Entity("bpm_mcp_api.Models.EmployeeExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeExpenses");
                });

            modelBuilder.Entity("bpm_mcp_api.Models.PurchaseRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Employee")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Requestor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PurchaseRequests");
                });

            modelBuilder.Entity("bpm_mcp_api.Models.PurchaseRequestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PurchaseRequestId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseRequestId");

                    b.ToTable("PurchaseRequestItems");
                });

            modelBuilder.Entity("bpm_mcp_api.Models.TravelExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TravelRequestId")
                        .HasColumnType("int");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TravelRequestId");

                    b.ToTable("TravelExpenses");
                });

            modelBuilder.Entity("bpm_mcp_api.Models.TravelRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartureCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinationCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TravelRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartureCity = "New York",
                            DepartureDate = new DateTime(2026, 1, 31, 10, 6, 15, 760, DateTimeKind.Local).AddTicks(3996),
                            DestinationCity = "Los Angeles",
                            Purpose = "Client meeting and conference",
                            RequestDate = new DateTime(2026, 1, 16, 10, 6, 15, 760, DateTimeKind.Local).AddTicks(4013),
                            RequestId = "TR-2024-001",
                            ReturnDate = new DateTime(2026, 2, 5, 10, 6, 15, 760, DateTimeKind.Local).AddTicks(4012),
                            Type = "Business"
                        },
                        new
                        {
                            Id = 2,
                            DepartureCity = "Chicago",
                            DepartureDate = new DateTime(2026, 2, 10, 10, 6, 15, 760, DateTimeKind.Local).AddTicks(4015),
                            DestinationCity = "San Francisco",
                            Purpose = "Technical training workshop",
                            RequestDate = new DateTime(2026, 1, 19, 10, 6, 15, 760, DateTimeKind.Local).AddTicks(4016),
                            RequestId = "TR-2024-002",
                            ReturnDate = new DateTime(2026, 2, 12, 10, 6, 15, 760, DateTimeKind.Local).AddTicks(4015),
                            Type = "Training"
                        });
                });

            modelBuilder.Entity("bpm_mcp_api.Models.PurchaseRequestItem", b =>
                {
                    b.HasOne("bpm_mcp_api.Models.PurchaseRequest", null)
                        .WithMany("Items")
                        .HasForeignKey("PurchaseRequestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("bpm_mcp_api.Models.TravelExpense", b =>
                {
                    b.HasOne("bpm_mcp_api.Models.TravelRequest", null)
                        .WithMany()
                        .HasForeignKey("TravelRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("bpm_mcp_api.Models.PurchaseRequest", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
